### ISSUE TITLE
error in the script

### ISSUE THREAD

**Issue by Adam24** [digital-dreamer/twister-proxy#8]
NodeJS is complaining there's an error in your script when I try to run it:

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1218:19)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at Object.<anonymous> (C:\Users\Adam24\AppData\Roaming\Twister\twister-proxy
-master\twister-proxy.js:209:24)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by digital-dreamer** [comment]
Hi Adam, Node.js doesn't allow normal users to start services on port numbers lower than 1024 (such as standard HTTP port 80) for security reasons. There are two ways to resolve it:

1 - Edit settings.json and change `"http_port": 80` to a higher number. It will then run under any user.

or

2 - If you want to use standard HTTP port, run the server as root: `sudo node twister-proxy.js &`

This is already explained in the readme file, but I forgot to handle the exception and display a meaningful message there so that the "listen EACCES" doesn't confuse people, thanks for reminding me.

**Comment by Adam24** [comment]
But how would I run as root on the Windows command prompt?

On Sunday, September 27, 2015, digital-dreamer <notifications@github.com>
wrote:

> Hi Adam, Node.js doesn't allow normal users to start services on port
> numbers lower than 1024 (such as standard HTTP port 80) for security
> reasons. There are two ways to resolve it:
>
> 1 - Edit settings.json and change "http_port": 80 to a higher number. It
> will then run under any user.
>
> or
>
> 2 - If you want to use standard HTTP port, run the server as root: sudo
> node twister-proxy.js &
>
> This is already explained in the readme file, but I forgot to handle the
> exception and display a meaningful message there so that the "listen
> EACCES" doesn't confuse people, thanks for reminding me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digital-dreamer/twister-proxy/issues/8#issuecomment-143528660>
> .
>


-- 
--Adam Robertson-- (write back)
